### ISSUE TITLE
Bible Corpus Downloading Issues

### ISSUE THREAD

**Issue by hinantin** [christos-c/bible-corpus-tools#1]
I recently tried to download the bible corpus at your website (http://christos-c.com/bible/), but the link seems to be broken:

![captura_de_pantalla_032815_104504_am](https://cloud.githubusercontent.com/assets/2458287/6881664/81b2ee3a-d537-11e4-8559-6ab104a6206d.jpg)

The single files ofr each language seems to be corrupted as well.

![captura_de_pantalla_032815_104605_am](https://cloud.githubusercontent.com/assets/2458287/6881669/a3ab36fa-d537-11e4-824e-0c37bfb60864.jpg)

**Comment by christos-c** [comment]
Thanks for notifying me. I have fixed the problem now. I apologise for the inconvenience.

**Comment by christos-c** [comment]
I have now removed the complicated download script from the website. Every translation (and the whole collection) is now an individual link.
