### ISSUE TITLE
Swedish data has empty lines (after doing alignment)

### ISSUE THREAD

**Issue by rasoolims** [christos-c/bible-corpus-tools#2]
Swedish data has empty lines (after doing alignment with your code) ---- I could resolve it by removing empty lines and striping sentence spaces. This is still problematic when trying to extract parallel data (e.g. German-Swedish)

**Comment by christos-c** [comment]
Is this after running `bible.CreateMLBooks XML_Bibles` (the first stage) or `bible.CreateVerseAlignedBooks XML_Bibles` (the second)? 
Also, what languages did you align Swedish to? This might be a specific language pair problem that I can look into.

**Comment by rasoolims** [comment]
It was after CreateVerseAlignedBooks

I tried to align some European languages: English, German, Swedish, French, Spanish, Portuguese and Italian. Swedish was the only problematic one.

**Comment by christos-c** [comment]
I fixed the problem. Turns out there was an XML tag `<spärr>` along with extra new lines that I somehow missed during my conversion/clean up. I have uploaded the new Swedish version on my website. Thanks for catching this!
