### ISSUE TITLE
Number of lines per verse is different after getting alignment

### ISSUE THREAD

**Issue by rasoolims** [christos-c/bible-corpus-tools#3]
I ran the following on https://github.com/christos-c/bible-corpus data (after gzipping the files):

> java -Xmx3g -cp lib/_:bin bible.CreateMLBooks ../../data/bible-corpus/bibles/
> java -cp lib/_:bin bible.CreateVerseAlignedBooks  ../../data/bible-corpus/bibles/

Here is an example wc on one of the created folders (Chinese and English have different number of lines):

> wc -l  ../../data/bible-corpus/bibles/aligned/10-b.2SA/*.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Afrikaans.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Albanian.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Arabic.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Bulgarian.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Cebuano.txt
>    1284 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Chinese.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Creole.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Croatian.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Czech.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Danish.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Dutch.txt
>    1284 ../../data/bible-corpus/bibles/aligned/10-b.2SA/English.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Esperanto.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Estonian.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Farsi.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Finnish.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/French.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/German.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Greek.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Hebrew.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Hindi.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Hungarian.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Icelandic.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Indonesian.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Italian.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Japanese.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Kannada.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Korean.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Latin.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Lithuanian.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Malagasy.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Malayalam.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Maori.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Marathi.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Myanmar.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Nepali.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Norwegian.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Paite.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Polish.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Portuguese.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Q'eqchi'.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Romanian.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Russian.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Serbian.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Slovak.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Slovene.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Somali.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Spanish.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Swedish.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Tagalog.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Telugu.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Thai.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Turkish.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Vietnamese.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Xhosa.txt
>     589 ../../data/bible-corpus/bibles/aligned/10-b.2SA/Zarma.txt
> 
> wc -l  ../../data/bible-corpus/bibles/aligned/53-b.2TH/*.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Afrikaans.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Albanian.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Arabic.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Bulgarian.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Cebuano.txt
>     85 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Chinese.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Creole.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Croatian.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Czech.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Danish.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Dutch.txt
>     85 ../../data/bible-corpus/bibles/aligned/53-b.2TH/English.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Esperanto.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Estonian.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Farsi.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Finnish.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/French.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/German.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Greek.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Hebrew.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Hindi.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Hungarian.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Icelandic.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Indonesian.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Italian.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Japanese.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Kannada.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Korean.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Latin.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Lithuanian.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Malagasy.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Malayalam.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Maori.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Marathi.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Myanmar.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Nepali.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Norwegian.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Paite.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Polish.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Portuguese.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Q'eqchi'.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Romanian.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Russian.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Serbian.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Slovak.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Slovene.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Somali.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Spanish.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Swedish.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Tagalog.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Telugu.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Thai.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Turkish.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Vietnamese.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Xhosa.txt
>     38 ../../data/bible-corpus/bibles/aligned/53-b.2TH/Zarma.txt

**Comment by christos-c** [comment]
@rasoolims thanks for catching this; it had to do with multiple versions of the same language. 
Make sure to checkout the latest version of the bible-corpus as it contains some fixes related to the XML of some bibles
