### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by i55code** [christos-c/bible-corpus-tools#4]
Hi Chris,

Hope all is well! I am using Java 1.7, and compiling the code at first step produces error: 

javac -cp "lib/*" -d bin src/bible/readers/*.java src/bible/*.java
src/bible/readers/BibleOrgHTMLReader.java:61: error: cannot find symbol
                    String verseText = String.join(" ", lineTokens.subList(1, lineTokens.size()));
                                             ^
  symbol:   method join(String,List<String>)
  location: class String
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

Please take a look and thank you so much! 

Cheers, 
Zhong

**Comment by christos-c** [comment]
Hi @zhongzho, thanks for catching this. `String.join()` is a Java 8 method. I have now changed this to the Apache commons equivalent so the code should compile under Java 7.
